# Generated by Django 6.0.4 on 2026-04-14 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='models/')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('ready', 'Готов к печати'), ('printed', 'Напечатано')], default='draft', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
