# Generated by Django 6.0.4 on 2026-05-12 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model3d',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='model3d',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='model3d',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='model3d',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='file',
            field=models.FileField(upload_to='models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj', 'step', '3mf'])]),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='material',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('ready', 'Готов к печати'), ('printed', 'Напечатано')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='version',
            field=models.CharField(db_index=True, default='1.0', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='model3d',
            unique_together={('name', 'version')},
        ),
    ]
