# Generated by Django 6.0.4 on 2026-05-13 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0003_category_model3d_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='model3d',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='models_manager.category'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Загрузка модели'), ('status_change', 'Изменение статуса'), ('material_change', 'Изменение материала'), ('delete', 'Удаление модели'), ('move', 'Перемещение между папками'), ('set_active', 'Установка активной версии'), ('category_create', 'Создание папки'), ('category_delete', 'Удаление папки')], max_length=50, verbose_name='Действие')),
                ('model_name', models.CharField(blank=True, max_length=200, verbose_name='Модель/папка')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'ordering': ['-timestamp'],
            },
        ),
    ]
