# Generated by Django 6.0.4 on 2026-05-13 15:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0004_alter_category_options_alter_model3d_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='model3d',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='model3d',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '3D модель', 'verbose_name_plural': '3D модели'},
        ),
        migrations.RemoveField(
            model_name='model3d',
            name='description',
        ),
        migrations.RemoveField(
            model_name='model3d',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='model3d',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='file',
            field=models.FileField(upload_to='models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj', 'step', '3mf'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='material',
            field=models.CharField(blank=True, max_length=50, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('ready', 'Готов к печати'), ('printed', 'Напечатано')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='version',
            field=models.CharField(db_index=True, default='1.0', max_length=20, verbose_name='Версия'),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
