# Generated by Django 6.0.4 on 2026-05-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Номер заказа'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
