# Generated by Django 6.0.4 on 2026-05-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0009_model3d_order_number_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='order_number',
        ),
    ]
