# Generated by Django 6.0.4 on 2026-05-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0010_remove_model3d_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='customer_email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название модели'),
        ),
    ]
